---

###gcp-instances-fixes###

# NOTA: estos fixes son por problemas que hemos tenido con las instancias en GCP en diferentes situacion como despues de reiniciar, conectarse mucho por SSH, etc.

# Fix para problema de read only filesystem  en instancias GCP
# NOTA: esto se debe ejecutar antes que todo lo demas porque sino falla todo.
# NOTA2: de esta operacion 1ro se guarda un log en memoria y despues desde ahi se guarda en el sistema de archivos, ya que sino fallaria si el sistema de archivos esta en modo Read Only.

- 
  name: "Fix RO filesystem - Remount filesystem with read-write mode"
  become: yes #sudo
  mount:
    src: "{{gcp_inst_fix_rofs_src}}"
    path: "{{gcp_inst_fix_rofs_path}}"
    fstype: "{{gcp_inst_fix_rofs_fstype}}"
    opts: remount,rw
    state: mounted
  when:
    - gcp_inst_fix_readonly_filesystem is defined
    - gcp_inst_fix_readonly_filesystem == true

-
  name: "Fix RO filesystem - Schedule Remount filesystem with read-write mode at Reboot"
  become: yes #sudo
  cron:
    name: gcp-readonly-filesystem-fix
    state: present
    special_time: reboot
    job: sleep {{gcp_inst_fix_readonly_filesystem_sleep}}; NAVENT_LOG_CRON_SCHEDULE_READONLY_FILESYSTEM_FIX=`mount -v -o remount,rw /`; echo $NAVENT_LOG_CRON_SCHEDULE_READONLY_FILESYSTEM_FIX > "/tmp/schedule-gcp-readonly-filesystem-fix-`date +%Y-%m-%d-%H-%M-%S`.log";
  when:
    - gcp_inst_fix_readonly_filesystem is defined
    - gcp_inst_fix_readonly_filesystem == true
    - gcp_inst_fix_readonly_filesystem_schedule is defined
    - gcp_inst_fix_readonly_filesystem_schedule == true



# Fix para problema de SSH timeout en instancias GCP debido al sshguard

- name: "Fix SSH timeout - Stop and Disable sshguard service"
  become: yes #sudo
  service:
    name: sshguard
    state: stopped
    enabled: "{{gcp_inst_fix_ssh_sshguard_enabled}}"
  when:
    - gcp_inst_fix_sshguard_timeout is defined
    - gcp_inst_fix_sshguard_timeout == true

-
  name: "Fix SSH timeout - Schedule Stop and Disable sshguard service at Reboot"
  become: yes #sudo
  cron:
    name: gcp-sshguard-timeout-fix
    state: present
    special_time: reboot
    job: "sleep {{gcp_inst_fix_sshguard_timeout_sleep}}; systemctl disable sshguard; systemctl stop sshguard;"
  when:
    - gcp_inst_fix_sshguard_timeout is defined
    - gcp_inst_fix_sshguard_timeout == true
    - gcp_inst_fix_sshguard_timeout_schedule is defined
    - gcp_inst_fix_sshguard_timeout_schedule == true



# Fix para problema de falla de resolucion de dominios DNS en instancias GCP

- 
  name: "Fix DNS resolution fail - Enable and Restart service 'systemd-resolved' (DNS)"
  become: yes #sudo
  systemd:
    name: systemd-resolved
    state: restarted
    enabled: "{{gcp_inst_fix_ssh_sd_resolved_enabled}}"
  when:
    - gcp_inst_fix_dns_resolution_fail is defined
    - gcp_inst_fix_dns_resolution_fail == true

-
  name: "Fix DNS resolution fail - Schedule Enable and Restart service 'systemd-resolved' (DNS) at Reboot"
  become: yes #sudo
  cron:
    name: gcp-dns-resolution-fail-fix
    state: present
    special_time: reboot
    job: "sleep {{gcp_inst_fix_dns_resolution_fail_sleep}}; systemctl enable systemd-resolved; systemctl restart systemd-resolved;"
  when:
    - gcp_inst_fix_dns_resolution_fail is defined
    - gcp_inst_fix_dns_resolution_fail == true
    - gcp_inst_fix_dns_resolution_fail_schedule is defined
    - gcp_inst_fix_dns_resolution_fail_schedule == true


